# Generated by Django 5.0.6 on 2024-08-16 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=255)),
                ('Desc', models.CharField(max_length=300)),
                ('pub_data', models.DateField()),
            ],
        ),
    ]
