# Generated by Django 5.0.6 on 2024-09-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
    ]
